name: csv-profiler-main
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.7
  - pandas>=1.5.0
  - numpy>=1.24.0
  - scipy>=1.10.0
  - matplotlib>=3.6.0
  - seaborn>=0.12.0
  - scikit-learn>=1.2.0
  - statsmodels>=0.13.0
  - tqdm>=4.64.0
  - pip
  - pip:
    - tableone>=0.7.12
    - missingno>=0.5.2
    - tabulate>=0.9.0