name: csv-profiler-main
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.7
  - pandas=2.3.1
  - numpy=2.2.6
  - scipy=1.13.1
  - matplotlib-base
  - seaborn=0.13.2
  - scikit-learn>=1.2.0
  - statsmodels>=0.13.0
  - tqdm=4.67.1
  - tableone=0.9.5
  - tabulate=0.9.0
  - researchpy=0.3.6
  - missingno>=0.5.2