# AutoCSV Profiler Suite - Master Configuration
# Single source of truth that generates environment-specific configurations
#
# LICENSE NOTICE: This configuration file is part of AutoCSV Profiler Suite
# and is distributed under the MIT License. Third-party packages referenced
# in environment specifications remain under their original licenses.
# Users are responsible for license compliance of installed packages.

# ==========================================
# PROJECT METADATA
# ==========================================
project:
  name: "autocsv-profiler-suite"
  version: "2.0.0"
  description: "Multi-environment CSV data analysis suite with isolated profiling engines"
  author: "dhaneshbb"
  author_email: "dhaneshbb5@gmail.com"
  license: "MIT"
  status: "Beta"
  repository: "https://github.com/dhaneshbb/autocsv-profiler-suite"
  min_python_version: "3.10"

# ==========================================
# MULTI-ENVIRONMENT DEFINITIONS
# ==========================================
environments:
  main:
    name: "csv-profiler-main"
    python_version: "3.11"
    description: "Core statistical analysis and delimiter detection"
    conda_packages:
      - "python=3.11.7"
      - "pandas=2.3.1"
      - "numpy=2.2.6"
      - "scipy=1.13.1"
      - "matplotlib-base=3.10.5"
      - "seaborn=0.13.2"
      - "tqdm=4.67.1"
      - "pyyaml=6.0.2"
      - "psutil=7.0.0"
      - "charset-normalizer>=3.0.0"
      - "tableone=0.9.5"
      - "tabulate=0.9.0"
      - "researchpy=0.3.6"
      - "rich=14.1.0"
    # Environment variables to prevent Qt backend usage
    environment_variables:
      MPLBACKEND: "Agg"
      MATPLOTLIB_BACKEND: "Agg"

  profiling:
    name: "csv-profiler-profiling"
    python_version: "3.10"
    description: "YData profiling and SweetViz report generation"
    conda_packages:
      - "python=3.10.4"
      - "pandas=2.3.1"
      - "numpy=1.24.4"
      - "ydata-profiling=4.16.1"
      - "sweetviz=2.3.1"
      - "charset-normalizer>=3.0.0"
      - "psutil=7.0.0"

  dataprep:
    name: "csv-profiler-dataprep"
    python_version: "3.10"
    description: "DataPrep EDA analysis"
    conda_packages:
      - "python=3.10.4"
      - "pandas=1.5.3"
      - "numpy=1.24.4"
      - "matplotlib-base"
      - "dataprep=0.4.5"
      - "charset-normalizer>=3.0.0"
      - "psutil=7.0.0"
    # Environment variables to prevent GPL backend usage
    environment_variables:
      MPLBACKEND: "Agg"
      MATPLOTLIB_BACKEND: "Agg"

# ==========================================
# ENGINE SCRIPTS CONFIGURATION
# ==========================================
scripts:
  - id: 1
    name: "engines/main/analyzer.py"
    environment: "main"
    description: "Core statistical analysis"
    args_type: "csv_delimiter_output"

  - id: 2
    name: "engines/profiling/ydata_report.py"
    environment: "profiling"
    description: "YData profiling report generation"
    args_type: "csv_delimiter_output"

  - id: 3
    name: "engines/profiling/sweetviz_report.py"
    environment: "profiling"
    description: "SweetViz report generation"
    args_type: "csv_delimiter_output"

  - id: 4
    name: "engines/dataprep/dataprep_report.py"
    environment: "dataprep"
    description: "DataPrep EDA report generation"
    args_type: "csv_delimiter_output"

# ==========================================
# APPLICATION SETTINGS
# ==========================================
app:
  # Performance Settings
  performance:
    chunk_size: 10000
    memory_limit_gb: 1
    max_file_size_mb: 500
    small_file_threshold_mb: 50
    encoding_sample_size: 8192
    chunk_estimate_factor: 1024

  # Delimiter Detection
  delimiter_detection:
    enabled: true
    confidence_threshold: 0.7
    sample_lines: 20
    common_delimiters: [",", ";", "\t", "|", ":", " "]

  # Analysis Settings
  analysis:
    high_cardinality_threshold: 20
    decimal_precision: 4
    quantiles: [0.25, 0.50, 0.75]

  # Validation Safety Limits
  validation:
    max_chunk_size: 100000
    max_memory_limit_gb: 32

  # Logging Configuration
  logging:
    level: "INFO"
    console:
      enabled: true
      level: "INFO"
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file:
      enabled: true
      level: "DEBUG"
      format: "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s"
      filename: "autocsv_profiler.log"
      max_bytes: 10485760
      backup_count: 5
    app:
      user_interaction: true
      analysis_progress: true
      performance_metrics: false
      structured_debug: false

  # File Encoding
  encoding:
    fallback_encodings: ["utf-8", "utf-8-sig", "latin1", "iso-8859-1", "cp1252", "ascii"]
